name: EasyTeleportPoint
version: 1.1.0
main: pers.zhangyang.easyteleportpoint.EasyTeleportPoint
api-version: 1.13
commands:
  EasyTeleportPoint:
    aliases: etp
softdepend:
  - Vault
  - PlaceholderAPI